
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lerha
 */
public class urunEkrani extends javax.swing.JDialog {
    DefaultTableModel model;
    urunİslemleri islemler = new urunİslemleri();
    /**
     * Creates new form urunEkrani
     */
    public urunEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = ( DefaultTableModel)urunTablosu.getModel();
        urunGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kategori_alani = new javax.swing.JComboBox();
        marka_alani = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fiyat_alani = new javax.swing.JTextField();
        stokSayisi_alani = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        magazaismi_alani = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        urunTablosu = new javax.swing.JTable();
        urun_ekle = new javax.swing.JButton();
        urun_sil = new javax.swing.JButton();
        urun_guncellestir = new javax.swing.JButton();
        mesaj_alani = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        arama_cubugu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 300, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(180, 247, 237));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/category-icon.png"))); // NOI18N
        jLabel2.setText("Kategori :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 100, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(180, 247, 237));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Television-icon.png"))); // NOI18N
        jLabel3.setText("Marka / Model : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        kategori_alani.setBackground(new java.awt.Color(204, 204, 204));
        kategori_alani.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laptop", "Telefon", "Tablet", "Televizyon", "Klavye/Mouse", "Fotoğraf Makinesi", "Yazıcı", "Kulaklık" }));
        getContentPane().add(kategori_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, 30));

        marka_alani.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(marka_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(180, 247, 237));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ecommerce-Price-Tag-Pound-icon.png"))); // NOI18N
        jLabel4.setText("Fiyat :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 80, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(180, 247, 237));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ecommerce-Move-By-Trolley-icon (1).png"))); // NOI18N
        jLabel5.setText("Stok Sayısı :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, 40));

        fiyat_alani.setBackground(new java.awt.Color(240, 240, 240));
        fiyat_alani.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(fiyat_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, 30));

        stokSayisi_alani.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(stokSayisi_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 160, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(180, 247, 237));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/store-icon.png"))); // NOI18N
        jLabel6.setText("Mağaza İsmi :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 40));

        magazaismi_alani.setBackground(new java.awt.Color(240, 240, 240));
        getContentPane().add(magazaismi_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 160, 30));

        urunTablosu.setBackground(new java.awt.Color(240, 240, 240));
        urunTablosu.setFont(new java.awt.Font("Sitka Heading", 3, 14)); // NOI18N
        urunTablosu.setForeground(new java.awt.Color(0, 153, 153));
        urunTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "         id", "Kategori", "Marka / Model", "Stok Sayısı", "Fiyat", "Mağaza İsmi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        urunTablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urunTablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urunTablosu);
        if (urunTablosu.getColumnModel().getColumnCount() > 0) {
            urunTablosu.getColumnModel().getColumn(0).setResizable(false);
            urunTablosu.getColumnModel().getColumn(1).setResizable(false);
            urunTablosu.getColumnModel().getColumn(2).setResizable(false);
            urunTablosu.getColumnModel().getColumn(3).setResizable(false);
            urunTablosu.getColumnModel().getColumn(4).setResizable(false);
            urunTablosu.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 580, 330));

        urun_ekle.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        urun_ekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Package-add-icon.png"))); // NOI18N
        urun_ekle.setText("Ürün Ekle");
        urun_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(urun_ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 170, 30));

        urun_sil.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        urun_sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Package-delete-icon.png"))); // NOI18N
        urun_sil.setText("Ürün Sil");
        urun_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_silActionPerformed(evt);
            }
        });
        getContentPane().add(urun_sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 170, 30));

        urun_guncellestir.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        urun_guncellestir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh-4-icon.png"))); // NOI18N
        urun_guncellestir.setText("Ürün Güncelleştir");
        urun_guncellestir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun_guncellestirActionPerformed(evt);
            }
        });
        getContentPane().add(urun_guncellestir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 170, 30));

        mesaj_alani.setEditable(false);
        mesaj_alani.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        mesaj_alani.setForeground(new java.awt.Color(0, 153, 153));
        mesaj_alani.setText("İşlem bekleniyor..");
        getContentPane().add(mesaj_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 290, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-icon.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 40, 50));

        arama_cubugu.setBackground(new java.awt.Color(240, 240, 240));
        arama_cubugu.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        arama_cubugu.setForeground(new java.awt.Color(0, 153, 153));
        arama_cubugu.setText("Aramak istediğiniz ürünü giriniz..");
        arama_cubugu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arama_cubuguMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                arama_cubuguMousePressed(evt);
            }
        });
        arama_cubugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arama_cubuguActionPerformed(evt);
            }
        });
        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });
        getContentPane().add(arama_cubugu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 510, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/e35516b91d2f6bb82cc47800be588465.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void tebriklerAudio(){
        try {
            AudioInputStream stream = AudioSystem.getAudioInputStream(new File("tebrikler.wav"));
            
            Clip clip =AudioSystem.getClip();
            clip.open(stream);
            clip.start();
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
    public void silUrunSecAudio(){
        try {
            AudioInputStream stream = AudioSystem.getAudioInputStream(new File("silUrunSec.wav"));
            
            Clip clip =AudioSystem.getClip();
            clip.open(stream);
            clip.start();
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
    public void urunTablosuBosAudio(){
        try {
            AudioInputStream stream = AudioSystem.getAudioInputStream(new File("urunTablosuBos.wav"));
            
            Clip clip =AudioSystem.getClip();
            clip.open(stream);
            clip.start();
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
    public void silmeBosAudio(){
        try {
            AudioInputStream stream = AudioSystem.getAudioInputStream(new File("bosSilme.wav"));
            
            Clip clip =AudioSystem.getClip();
            clip.open(stream);
            clip.start();
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
    public void guncelLenecekUrunAudio(){
        try {
            AudioInputStream stream = AudioSystem.getAudioInputStream(new File("guncelUrunSec.wav"));
            
            Clip clip =AudioSystem.getClip();
            clip.open(stream);
            clip.start();
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(urunİslemleri.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
    private void urun_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_ekleActionPerformed
      mesaj_alani.setText("");
      String kategori = kategori_alani.getSelectedItem().toString();
      String marka = marka_alani.getText();
      String fiyat = fiyat_alani.getText();
      String stok = stokSayisi_alani.getText();
      String magaza = magazaismi_alani.getText();
      islemler.urunEkle(kategori,marka,fiyat,stok,magaza);
      mesaj_alani.setText("Yeni ürün başarıyla eklendi !");
      tebriklerAudio();
      urunGoruntule();
      girilenleriTemizle();
    }//GEN-LAST:event_urun_ekleActionPerformed
    public void dinamikAra(String ara){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        
        urunTablosu.setRowSorter(tr);
    
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
      String ara = arama_cubugu.getText();
      dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void urunTablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urunTablosuMouseClicked
       int selectedRow = urunTablosu.getSelectedRow();
       marka_alani.setText(model.getValueAt(selectedRow,2).toString());
       fiyat_alani.setText(model.getValueAt(selectedRow,4).toString());
       stokSayisi_alani.setText(model.getValueAt(selectedRow, 3).toString());
       magazaismi_alani.setText(model.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_urunTablosuMouseClicked

    private void arama_cubuguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arama_cubuguActionPerformed
        
    }//GEN-LAST:event_arama_cubuguActionPerformed

    private void arama_cubuguMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arama_cubuguMouseClicked
        arama_cubugu.setText("");
    }//GEN-LAST:event_arama_cubuguMouseClicked

    private void urun_guncellestirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_guncellestirActionPerformed
       String marka = marka_alani.getText();
        String fiyat = fiyat_alani.getText();
        String stok = stokSayisi_alani.getText();
        String magaza = magazaismi_alani.getText();
        String kategori = kategori_alani.getSelectedItem().toString();
        
        int selectedRow = urunTablosu.getSelectedRow();
        if(selectedRow == -1){
            if(model.getRowCount()== 0){
                mesaj_alani.setText("Ürünler tablosu boş. Güncelleme işlemi başarısız oldu!");
                urunTablosuBosAudio();
            }else{
                mesaj_alani.setText("Lütfen güncellenecek bir ürün seçiniz !");
                guncelLenecekUrunAudio();
            }
        }else{
            
            int id = (int) model.getValueAt(selectedRow, 0);
            
            islemler.urunGuncelle(id,kategori,marka,fiyat,stok,magaza);
            urunGoruntule();
            mesaj_alani.setText("Ürün tablonuz başarıyla güncellendi");
            tebriklerAudio();
            girilenleriTemizle();
        }
    }//GEN-LAST:event_urun_guncellestirActionPerformed

    private void urun_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun_silActionPerformed
       mesaj_alani.setText("");
       int selectedRow = urunTablosu.getSelectedRow();
       if(selectedRow == -1){
           
           if(model.getRowCount() == 0){
               mesaj_alani.setText("Ürün tablosu şuanda boş. Silme işlemi başarısız oldu !");
               silmeBosAudio();
               
           }else{
               mesaj_alani.setText("Lütfen silinecek bir ürün seçiniz !");
               silUrunSecAudio();
           }
           
       }else{
           int id =(int) model.getValueAt(selectedRow, 0);
           islemler.urunuSil(id);
           urunGoruntule();
           mesaj_alani.setText("Seçtiğiniz ürün başarıyla silindi !");
           tebriklerAudio();
           girilenleriTemizle();
       }
    }//GEN-LAST:event_urun_silActionPerformed

    private void arama_cubuguMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arama_cubuguMousePressed
        arama_cubugu.setText("");
    }//GEN-LAST:event_arama_cubuguMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(urunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(urunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(urunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(urunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                urunEkrani dialog = new urunEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void urunGoruntule(){
        model.setRowCount(0);
        ArrayList<urun> urunler =new ArrayList<urun>();
        urunler = islemler.urunleriGetir();
        if(urunler != null){
            for(urun Urun : urunler){
                Object [] eklenecek = {Urun.getId(),Urun.getKategori(),Urun.getUrunİsmi(),Urun.getFiyat(),Urun.getStokSayisi(),Urun.getMagazaİsmi()};
                model.addRow(eklenecek);
            }
        }
    }
    public void girilenleriTemizle(){
     marka_alani.setText("");
     fiyat_alani.setText("");
     magazaismi_alani.setText("");
     stokSayisi_alani.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JTextField fiyat_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox kategori_alani;
    private javax.swing.JTextField magazaismi_alani;
    private javax.swing.JTextField marka_alani;
    private javax.swing.JTextField mesaj_alani;
    private javax.swing.JTextField stokSayisi_alani;
    private javax.swing.JTable urunTablosu;
    private javax.swing.JButton urun_ekle;
    private javax.swing.JButton urun_guncellestir;
    private javax.swing.JButton urun_sil;
    // End of variables declaration//GEN-END:variables
}
